<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpmailer/src/Exception.php';
require 'phpmailer/src/PHPMailer.php';
require 'phpmailer/src/SMTP.php';

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $email = $_POST["email"];
    $newPassword = $_POST["newPassword"];

    $servername = "localhost";
    $username = "root";
    $password = "";
    $dbname = "rgym";

    $conn = mysqli_connect($servername, $username, $password, $dbname);

    if (!$conn) {
        die("Database not connected: " . mysqli_connect_error());
    }

    $sql = "UPDATE users SET password='$newPassword' WHERE email='$email'";

    if (mysqli_query($conn, $sql)) {
        echo "Password Updated Successfully";

        $mail = new PHPMailer(true);

    $emailSender = 'rgymofficial@gmail.com';
    $emailSenderPassword = 'upck oexs tawr npbj';

        try {
            // Configure SMTP settings
            $mail->isSMTP();
            $mail->Host = 'smtp.gmail.com';
            $mail->SMTPAuth = true;
            $mail->Username = $emailSender;
            $mail->Password = $emailSenderPassword;
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port = 587;

            // Recipient information
            $mail->setFrom($emailSender, 'Automated-Mail, R-GYM');
            $mail->addAddress($email);
            $mail->addReplyTo($emailSender, 'Support R-GYM');

            // Email content
            $mail->isHTML(true);
            $mail->Subject = 'Password Change Notification - R-GYM';

            $emailContent = "
    <html>
    <head>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                color: #333333;
                margin: 0;
                padding: 20px;
            }

            #logo {
                font-size: 48px;
                font-weight: bold;
                color: #ffffff;
            }

            #container {
                max-width: 600px;
                margin: 0 auto;
            }

            #header {
                background-color: #007bff;
                padding: 20px;
                text-align: center;
            }

            #content {
                padding: 20px;
                background-color: #343a40;
                border-radius: 5px;
                text-align: left;
                color: #ffffff;
            }

            #footer {
                background-color: #333333;
                padding: 20px;
                text-align: center;
                color: #ffffff;
            }

            p {
                margin-bottom: 15px;
            }

            #password-change-confirmation {
                padding: 10px;
                border-radius: 5px;
                margin-top: 20px;
                color: #666666; /* Grey text color */
            }

            #password-change-confirmation p {
                margin: 0;
            }
        </style>
    </head>
    <body>
        <div id='container'>
            <div id='header'>
                <div id='logo'>R-GYM</div>
            </div>
            <div id='content' style='color:#ffffff'>
                <p>Dear User,</p>
                <p>Your R-GYM account password has been successfully changed.</p>
                <p>Your new password: <strong>$newPassword</strong></p>
                <p>If you did not make this change or have any concerns, please contact us immediately.</p>
                <div id='password-change-confirmation'>
                    <p>This email is autogenerated to inform you that your password has been changed successfully.</p>
                </div>
            </div>
            <div id='footer'>
                <p>Contact us at: info@rgym.com</p>
            </div>
        </div>
    </body>
    </html>
";


            $mail->Body = $emailContent;

            $mail->send();
            echo ' Email sent successfully';

            header("Location: reset.html");
            exit();
        } catch (Exception $e) {
            echo 'Failed to send email: ', $mail->ErrorInfo;
        }
    } else {
        echo "Error updating password: " . mysqli_error($conn);
    }

    mysqli_close($conn);
}

?>
